import Head from "next/head";

export default function ErrorPage() {
    return(
        <>
        <Head>
        <title>Página não encontrada</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href=""
        />
      </Head>
            <h2>Opss, página não encontrada</h2>
            <p>Tente novamente mais tarde</p>
        </>
    )
}